apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/kode-gcp-project/test-gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
        - name: port
          value: "5000"

